# Generated by Django 3.1.2 on 2020-11-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20201113_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(default='', editable=False, primary_key=True, serialize=False)),
                ('questionid', models.IntegerField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
