# Generated by Django 3.1.2 on 2020-11-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.IntegerField(default='', editable=False, primary_key=True, serialize=False)),
                ('name', models.IntegerField(blank=True, null=True)),
                ('describtion', models.TextField(blank=True, null=True)),
                ('mode', models.CharField(max_length=255)),
                ('celltype', models.CharField(max_length=255)),
                ('componenet', models.CharField(max_length=255)),
                ('doi', models.CharField(max_length=255)),
                ('organism', models.CharField(max_length=255)),
            ],
        ),
    ]
