# Generated by Django 3.1.2 on 2020-11-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20201113_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.IntegerField(default='', editable=False, primary_key=True, serialize=False),
        ),
    ]
