# Generated by Django 3.1.2 on 2020-11-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20201113_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='image',
        ),
    ]
