# Generated by Django 3.1.2 on 2020-11-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0010_auto_20201113_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
