# Generated by Django 3.1.2 on 2020-11-13 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizapp', '0011_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
        migrations.AddField(
            model_name='profile',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Score_Total'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
