# Generated by Django 3.1.2 on 2020-11-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_auto_20201113_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Score'),
        ),
    ]
