# Generated by Django 3.1.2 on 2020-11-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_auto_20201114_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.IntegerField(default='', editable=False, primary_key=True, serialize=False),
        ),
    ]
