# Generated by Django 3.1.2 on 2020-11-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_auto_20201116_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='componenet',
            new_name='component',
        ),
    ]
